services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: ["serve"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma

  agent:
    build: ./agent
    container_name: langchain-agent
    depends_on:
      - ollama
      - chroma
    ports:
      - "8501:8501"  # Streamlit UI
    working_dir: /workspace
    volumes:
      - ./agent:/workspace
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_URL=http://chroma:8000

volumes:
  ollama_data:
  chroma_data: